"""report.py — aggregate per-(ticker, timeframe) results into global summary.

Reads results/csv/*.csv and produces:
- results/summary/global_summary.csv (one row per (ticker, timeframe) with best Sharpe, etc.)
- results/summary/best_params_per_combo.csv
- results/summary/cross_ticker_heatmap.png
- paper/summary_table.tex (LaTeX-ready)
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

RESULTS_CSV = Path(__file__).resolve().parent.parent / "results" / "csv"
SUMMARY_DIR = Path(__file__).resolve().parent.parent / "results" / "summary"
SUMMARY_DIR.mkdir(parents=True, exist_ok=True)
PAPER_DIR = Path(__file__).resolve().parent.parent / "paper"
PAPER_DIR.mkdir(exist_ok=True)


def aggregate() -> pd.DataFrame:
    """Read all per-combo CSVs and produce global summary."""
    csvs = sorted(RESULTS_CSV.glob("*_summary.json"))
    rows = []
    for sp in csvs:
        with open(sp) as f:
            s = json.load(f)
        rows.append({
            "ticker": s["ticker"],
            "timeframe": s["timeframe"],
            "n_candles": s["n_candles"],
            "periods_per_year": s["periods_per_year"],
            "elapsed_s": s["elapsed_s"],
            "best_archer_sharpe": s["best_in_sweep"]["sharpe"],
            "best_n_mu": s["best_in_sweep"]["sharpe_params"]["n_mu"],
            "best_x": s["best_in_sweep"]["sharpe_params"]["x"],
            "best_bear_alloc": s["best_in_sweep"]["sharpe_params"]["bear_alloc_1d"],
            "best_ema_pair": s["best_in_sweep"]["sharpe_params"]["ema_pair"],
            "buy_and_hold_sharpe": s["baselines"]["buy_and_hold"]["sharpe"],
            "buy_and_hold_total_return": s["baselines"]["buy_and_hold"]["total_return"],
            "vanilla_ema_sharpe": s["baselines"]["vanilla_ema_cross"]["sharpe"],
            "vanilla_ema_total_return": s["baselines"]["vanilla_ema_cross"]["total_return"],
        })
    return pd.DataFrame(rows)


def cross_ticker_heatmap(df: pd.DataFrame, metric: str, out_path: Path) -> Path:
    """Heatmap: ticker (rows) x timeframe (cols), values = best Archer metric."""
    pivot = df.pivot_table(
        index="ticker", columns="timeframe", values=metric, aggfunc="first"
    )
    fig, ax = plt.subplots(figsize=(10, 6))
    im = ax.imshow(pivot.values, aspect="auto", cmap="RdYlGn", vmin=-1, vmax=3)
    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels(pivot.columns, rotation=45, ha="right")
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels(pivot.index)
    ax.set_title(f"Best {metric} per ticker per timeframe")
    plt.colorbar(im, ax=ax)
    for i in range(pivot.shape[0]):
        for j in range(pivot.shape[1]):
            v = pivot.values[i, j]
            if not np.isnan(v):
                ax.text(j, i, f"{v:.2f}", ha="center", va="center", color="black", fontsize=8)
    plt.tight_layout()
    plt.savefig(out_path, dpi=120)
    plt.close(fig)
    return out_path


def write_latex_table(df: pd.DataFrame, out_path: Path) -> Path:
    """Write a LaTeX tabular of the summary."""
    df = df.sort_values(["timeframe", "ticker"]).reset_index(drop=True)
    cols = [
        "ticker", "timeframe", "n_candles",
        "best_archer_sharpe", "best_n_mu", "best_x", "best_bear_alloc", "best_ema_pair",
        "buy_and_hold_sharpe", "vanilla_ema_sharpe",
    ]
    df = df[cols]
    with open(out_path, "w") as f:
        f.write("% Auto-generated by src/report.py — do not edit\n")
        f.write("\\begin{tabular}{llr" + "r" * 8 + "}\n")
        f.write("\\toprule\n")
        headers = ["Ticker", "TF", "N", "Best Archer", "n\\_mu", "x", "Bear", "EMA", "BnH Sharpe", "Vanilla Sharpe"]
        f.write(" & ".join(headers) + " \\\\\n")
        f.write("\\midrule\n")
        for _, r in df.iterrows():
            f.write(
                f"{r['ticker']} & {r['timeframe']} & {int(r['n_candles'])} & "
                f"{r['best_archer_sharpe']:.2f} & {int(r['best_n_mu'])} & "
                f"{r['best_x']:.2f} & {r['best_bear_alloc']:.2f} & "
                f"{r['best_ema_pair']} & {r['buy_and_hold_sharpe']:.2f} & "
                f"{r['vanilla_ema_sharpe']:.2f} \\\\\n"
            )
        f.write("\\bottomrule\n\\end{tabular}\n")
    return out_path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--in", dest="in_dir", default=str(RESULTS_CSV))
    parser.add_argument("--out", dest="out_dir", default=str(SUMMARY_DIR))
    parser.add_argument("--paper-dir", default=str(PAPER_DIR))
    args = parser.parse_args()
    df = aggregate()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_dir / "global_summary.csv", index=False)
    print(f"Wrote: {out_dir / 'global_summary.csv'} ({len(df)} rows)")
    # Cross-ticker heatmap
    p = cross_ticker_heatmap(df, "best_archer_sharpe", out_dir / "cross_ticker_archer_sharpe.png")
    print(f"Wrote: {p}")
    # LaTeX table
    paper_dir = Path(args.paper_dir)
    paper_dir.mkdir(parents=True, exist_ok=True)
    t = write_latex_table(df, paper_dir / "summary_table.tex")
    print(f"Wrote: {t}")


if __name__ == "__main__":
    main()
